"""Infrastructure layer for feng shui layout module.

This module provides the infrastructure implementations including:
- Tools: Collision detection, furniture database, RAG search, validation
- Geometry: Grid placement, collision detection, path finding
- Persistence: Furniture catalog, agent memory (future)
"""

from src.modules.layout.infrastructure.geometry import (
    AABB,
    CellState,
    ClearanceRequirement,
    CollisionDetector,
    CollisionResult,
    CollisionSeverity,
    GridPosition,
    GridRect,
    PathFinder,
    PathPoint,
    PathResult,
    PathType,
    PlacementCandidate,
    PlacementGrid,
    TrafficPath,
    calculate_path_efficiency,
    check_rotated_collision,
    find_direct_line_path,
)
from src.modules.layout.infrastructure.tools import (
    BaseTool,
    BudgetLevel,
    CatalogFurniture,
    ClarificationAnswer,
    ClarificationQuestion,
    ClarifierInput,
    ClarifierOutput,
    Collision,
    CollisionDetectorInput,
    CollisionDetectorOutput,
    CollisionDetectorTool,
    CollisionType,
    FENG_SHUI_RULES,
    FengShuiRule,
    FURNITURE_CATALOG,
    FurnitureSearchInput,
    FurnitureSearchOutput,
    FurnitureSearchResult,
    InMemoryFurnitureDbTool,
    LayoutItem,
    MockRagSearchTool,
    PlacedItem,
    QuestionPriority,
    QuestionStatus,
    QuestionType,
    RagSearchInput,
    RagSearchOutput,
    RuleCategory,
    RuleSearchResult,
    SpatialAnalysisInput,
    SpatialAnalysisOutput,
    SpatialCalculatorTool,
    ToolError,
    ToolInputError,
    ToolResult,
    ToolTimeoutError,
    UserClarifierTool,
    ValidationIssue,
    ValidationLevel,
    ValidatorInput,
    ValidatorOutput,
    ValidatorTool,
    Zone,
    ZoneType,
)

__all__ = [
    # Geometry - Collision
    "AABB",
    "ClearanceRequirement",
    "CollisionDetector",
    "CollisionResult",
    "CollisionSeverity",
    "check_rotated_collision",
    # Geometry - Grid
    "CellState",
    "GridPosition",
    "GridRect",
    "PlacementCandidate",
    "PlacementGrid",
    # Geometry - Path Finding
    "PathFinder",
    "PathPoint",
    "PathResult",
    "PathType",
    "TrafficPath",
    "calculate_path_efficiency",
    "find_direct_line_path",
    # Tools - Base
    "BaseTool",
    "ToolError",
    "ToolInputError",
    "ToolResult",
    "ToolTimeoutError",
    # Tools - Collision Detector
    "Collision",
    "CollisionDetectorInput",
    "CollisionDetectorOutput",
    "CollisionDetectorTool",
    "CollisionType",
    "PlacedItem",
    # Tools - Furniture DB
    "BudgetLevel",
    "CatalogFurniture",
    "FURNITURE_CATALOG",
    "FurnitureSearchInput",
    "FurnitureSearchOutput",
    "FurnitureSearchResult",
    "InMemoryFurnitureDbTool",
    # Tools - RAG Search
    "FENG_SHUI_RULES",
    "FengShuiRule",
    "MockRagSearchTool",
    "RagSearchInput",
    "RagSearchOutput",
    "RuleCategory",
    "RuleSearchResult",
    # Tools - Spatial Calculator
    "SpatialAnalysisInput",
    "SpatialAnalysisOutput",
    "SpatialCalculatorTool",
    "Zone",
    "ZoneType",
    # Tools - User Clarifier
    "ClarificationAnswer",
    "ClarificationQuestion",
    "ClarifierInput",
    "ClarifierOutput",
    "QuestionPriority",
    "QuestionStatus",
    "QuestionType",
    "UserClarifierTool",
    # Tools - Validator
    "LayoutItem",
    "ValidationIssue",
    "ValidationLevel",
    "ValidatorInput",
    "ValidatorOutput",
    "ValidatorTool",
]
