"""Domain layer for feng shui layout module."""

from src.modules.layout.domain.entities import (
    DoorPosition,
    Furniture,
    FurnitureCategory,
    FurnitureDimensions,
    Placement,
    Room,
    RoomType,
    WallSide,
    WindowPosition,
)
from src.modules.layout.domain.exceptions import (
    ClearanceViolationError,
    CollisionError,
    DoorBlockedError,
    EmergencyExitBlockedError,
    FengShuiAgentError,
    FurnitureDbError,
    InsufficientSpaceError,
    InvalidDoorPositionError,
    InvalidRoomDimensionsError,
    InvalidWindowPositionError,
    JsonValidationError,
    NoValidPlacementError,
    OutputError,
    OutputSizeError,
    PlacementError,
    RagSearchError,
    SafetyError,
    ScoringError,
    ToolError,
    ToolExecutionError,
    ToolInputError,
    ToolTimeoutError,
    ValidationError,
)
from src.modules.layout.domain.repositories import (
    AgentMemoryRepository,
    FurnitureRepository,
)
from src.modules.layout.domain.value_objects import (
    BoundingBox,
    FengShuiScore,
    Position3D,
    Rotation,
    RulePriority,
)

__all__ = [
    # Entities
    "DoorPosition",
    "Furniture",
    "FurnitureCategory",
    "FurnitureDimensions",
    "Placement",
    "Room",
    "RoomType",
    "WallSide",
    "WindowPosition",
    # Value Objects
    "BoundingBox",
    "FengShuiScore",
    "Position3D",
    "Rotation",
    "RulePriority",
    # Exceptions
    "ClearanceViolationError",
    "CollisionError",
    "DoorBlockedError",
    "EmergencyExitBlockedError",
    "FengShuiAgentError",
    "FurnitureDbError",
    "InsufficientSpaceError",
    "InvalidDoorPositionError",
    "InvalidRoomDimensionsError",
    "InvalidWindowPositionError",
    "JsonValidationError",
    "NoValidPlacementError",
    "OutputError",
    "OutputSizeError",
    "PlacementError",
    "RagSearchError",
    "SafetyError",
    "ScoringError",
    "ToolError",
    "ToolExecutionError",
    "ToolInputError",
    "ToolTimeoutError",
    "ValidationError",
    # Repositories
    "AgentMemoryRepository",
    "FurnitureRepository",
]
